AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Resources for users to post screenshots to s3 with public read permissions as an alternative to
  imgur

Parameters:

  S3BucketName:
    Type: String
    Description: S3 bucket to create to store images in.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: PublicRead

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: ShotputBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
      Bucket: !Ref S3Bucket

  PostToBucketIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "cognito-idp.amazonaws.com"
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: "PutScreenshots"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "s3:Put*"
                Resource: !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref S3Bucket
                    - /*

  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: True
      IdentityPoolName: Shotput

  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        "unauthenticated": !GetAtt PostToBucketIamRole.Arn

Outputs:
  IdentityPoolID:
    Description: ID of the Identity Pool
    Value: !Ref IdentityPool
    Export:
      Name: !Sub "${AWS::StackName}-identity-pool-id"

  S3BucketName:
    Description: Name of the S3 Bucket to store images in
    Value: !Ref S3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-s3-bucket-name"
